apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apimanager
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/exec", "secrets", "namespaces", "configmaps", "services", "endpoints", "authentication.k8s.io/token-review"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
