apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: macaron-default-clusterrole-binding
subjects:
- kind: ServiceAccount
  name: macaron-default
  namespace: default
roleRef:
  kind: ClusterRole
  name: apimanager
  apiGroup: rbac.authorization.k8s.io
